sudo: true
os: trusty
cache: false
env:
- URL=https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
before_install:
- openssl aes-256-cbc -K $encrypted_527a7bf57f17_key -iv $encrypted_527a7bf57f17_iv
  -in assets/server.key.enc -out assets/server.key -d
- export SFDX_AUTOUPDATE_DISABLE=false
- export SFDX_USE_GENERIC_UNIX_KEYCHAIN=true
- export SFDX_DOMAIN_RETRY=300
- export SFDX_DISABLE_APP_HUB=true
- export SFDX_LOG_LEVEL=DEBUG
- mkdir sfdx
- wget -qO- $URL | tar xJ -C sfdx --strip-components 1
- "./sfdx/install"
- export PATH=./sfdx/$(pwd):$PATH
- sfdx --version
- sfdx plugins --core
- sfdx force:auth:jwt:grant --clientid $CONSUMERKEY --jwtkeyfile assets/server.key
  --username $USERNAME --setdefaultdevhubusername -a HubOrg
script:
- |
  if ["$TRAVIS_COMMIT_MESSAGE" == "deploy full"]; then 
    sfdx force:source:convert -d deployPrepared/
    sfdx force:mdapi:deploy -d deployPrepared/ -u HubOrg
  else 
    echo "Commit message" + $TRAVIS_COMMIT_MESSAGE; 
    echo "Skip deployment to full"; 
  fi
- echo $TRAVIS_COMMIT;
- sfdx force:apex:test:run -u HubOrg --wait 10
