sudo: true
os: trusty
cache: false
env:
- DEPLOY_ENV="Test"
before_install:
- openssl aes-256-cbc -K $encrypted_527a7bf57f17_key -iv $encrypted_527a7bf57f17_iv
  -in assets/server.key.enc -out assets/server.key -d
- export SFDX_AUTOUPDATE_DISABLE=false
- export SFDX_USE_GENERIC_UNIX_KEYCHAIN=true
- export SFDX_DOMAIN_RETRY=300
- export SFDX_DISABLE_APP_HUB=true
- export SFDX_LOG_LEVEL=DEBUG
- mkdir sfdx
- wget -qO- https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz | tar xJ -C sfdx --strip-components 1
- "./sfdx/install"
- export PATH=./sfdx/$(pwd):$PATH
- sfdx --version
- sfdx plugins --core
- |
  if [ "$DEPLOY_ENV" == "FULL" ]; then 
    sfdx force:auth:jwt:grant --clientid $CONSUMERKEY --jwtkeyfile assets/server.key --username $USERNAME --setdefaultdevhubusername -a HubOrg
  fi
script:
- |
  if [ -z "$TESTS_TO_RUN" ]; then 
    TESTS_TO_RUN="mytest"
  fi
- |
  if [ "$DEPLOY_ENV" == "FULL" ]; then 
    sfdx force:source:convert -d deployPrepared/
    sfdx force:mdapi:deploy -d deployPrepared/ -u HubOrg -l RunSpecifiedTests -r $TESTS_TO_RUN --wait 10
    sfdx force:apex:test:run -u HubOrg --wait 10
  else 
    echo "Skip deployment to full"; 
  fi
